version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app
    env_file: ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
